version: '3.8'

services:
  backend:
    image: ${IMAGE_NAME:-backend}
    env_file: .env
    ports:
      - "${HOST_PORT_RANGE}:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
