- name: Setup Common Environment
  hosts: all
  become: true
  roles:
    - common
    - docker

- name: Configure App Server
  hosts: app_server
  become: true
  roles:
    - nginx
    - certbot

- name: Configure Stateful Server
  hosts: stateful_server
  become: true
  roles:
    - postgres
    - redis
    - rabbitmq
