---
- name: Add Certbot GPG key
  ansible.builtin.apt_key:
    keyserver: 'hkps://keyserver.ubuntu.com:443'
    id: '75BCA694' # Certbot's PPA key ID
    keyring: /usr/share/keyrings/certbot.gpg
    state: present

- name: Add Certbot repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/certbot.gpg] https://ppa.launchpadcontent.net/certbot/certbot/ubuntu jammy main'
    state: present
    filename: certbot
    update_cache: yes

- name: Install Certbot and dependencies
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
