- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create Nginx configuration
  template:
    src: nginx.conf.j2
    dest: '/etc/nginx/sites-available/{{ nginx_domain }}'
  notify: Restart Nginx

- name: Enable site
  file:
    src: '/etc/nginx/sites-available/{{ nginx_domain }}'
    dest: '/etc/nginx/sites-enabled/{{ nginx_domain }}'
    state: link

- name: Obtain SSL Certificate
  command: 'certbot certonly --nginx -d {{ nginx_domain }} --non-interactive --agree-tos -m admin@{{ nginx_domain }}'
  notify: Restart Nginx
